---

- name: Create users ldif file
  template: src=users.ldif.j2 dest={{ openldap_server_app_path }}/users.ldif
  register: users_copy

- name: Add Users
  when: users_copy.changed
  register: command_result
  failed_when: "command_result.rc not in [1,68]"
  shell: ldapadd -c -x -D "cn=Manager,dc={{ openldap_server_domain_name.split('.')[0] }},dc={{ openldap_server_domain_name.split('.')[1] }}" -w {{ openldap_server_rootpw }} -f {{ openldap_server_app_path }}/users.ldif 

