---

- name: Add the OS specific varibles
  include_vars: "{{ ansible_os_family }}.yml"

- name: Install the openldap and required Packages for RedHat
  yum: name={{ item }} state=installed
  with_items: ldap_pkgs
  when: ansible_os_family == 'RedHat'


- name: Install the openldap and required Packages for Ubuntu
  apt: name={{ item }} state=installed update_cache=yes
  with_items: ldap_pkgs
  environment: env
  when: ansible_os_family == 'Debian'

- name: Delete the configuration directory
  file: path={{ app_path }}/slapd.d state=absent

- name: Generate the root password for ldap
  shell: slappasswd -s {{ rootpw }} 
  register: root_password

- name: Copy the slapd.conf configuration file for Redhat
  template: src=slapd.conf.j2 dest={{ app_path }}/slapd.conf
  when: ansible_os_family == "RedHat"
  notify: 
   - restart slapd

- name: Copy the slapd.conf configuration file
  template: src=slapd.conf_ubuntu.j2 dest={{ app_path }}/slapd.conf
  when: ansible_os_family == "Debian"
  notify: 
   - restart slapd

- name: Copy the ldap.conf configuration file
  template: src=ldap.conf.j2 dest={{ app_path }}/ldap.conf

